# Generated by Django 4.2.1 on 2023-05-25 23:30

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nickname',
            field=models.CharField(default='사용자', max_length=50, verbose_name=users.models.User),
        ),
    ]
