# Generated by Django 4.2.1 on 2023-05-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(blank=True, max_length=20, verbose_name='태그'),
        ),
    ]
